# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticket_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_location',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_location',
            field=models.ManyToManyField(blank=True, null=True, to='events.TicketLocation'),
        ),
    ]
