# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160904_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_location',
            field=models.ManyToManyField(blank=True, to='events.TicketLocation'),
        ),
    ]
