# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(max_length=30)),
                ('zero_byte', models.BooleanField(default=False)),
                ('track', models.IntegerField()),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
