# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0002_auto_20160508_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='copyright',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
