# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0007_auto_20160830_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('icon', models.ImageField(upload_to=b'')),
                ('url', models.URLField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_store', to='discography.Album')),
            ],
        ),
    ]
