# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0008_musicstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='mp3',
            field=models.FileField(blank=True, null=True, upload_to='tracks'),
        ),
    ]
