# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0009_track_mp3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('font_awesome_class', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='musicstore',
            name='name',
        ),
        migrations.AddField(
            model_name='musicstore',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_music_store', to='discography.Track'),
        ),
        migrations.AlterField(
            model_name='musicstore',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_store', to='discography.Album'),
        ),
        migrations.AlterField(
            model_name='musicstore',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='musicstore',
            name='social_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discography.SocialIcon'),
        ),
    ]
