# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0010_auto_20170206_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicstore',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_music_store', to='discography.Album'),
        ),
    ]
